###
GET http://localhost:3000

###Fetch all the songs 
GET http://localhost:3000/songs

###find a song request 
GET http://localhost:3000/songs/2

###Create new song request 
POST http://localhost:3000/songs
Content-Type: application/json

{   "title":"Animals",
    "artists":["maroon 5"],
    "releaseDate":"2022-09-10",
    "duration":"02:34",
    "lyrics":""
}

###Update song request 
PUT http://localhost:3000/songs/1

###delete songs
DELETE http://localhost:3000/songs/1